import { PreviewControls } from './preview-controls';

export const dynamic = 'force-dynamic';

interface Example {
  title: string;
  note: string;
  end: string;
  theme?: string;
}

function isoUtc(msFromNow: number): string {
  return new Date(Date.now() + msFromNow).toISOString().replace(/\.\d{3}Z$/, 'Z');
}

function buildExamples(): Example[] {
  return [
    {
      title: '~3 days out',
      note: 'Typical mid-campaign state.',
      end: isoUtc(3 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000 + 27 * 60 * 1000),
    },
    {
      title: '~2 hours out',
      note: 'Last-chance send window.',
      end: isoUtc(2 * 60 * 60 * 1000 + 12 * 60 * 1000),
    },
    {
      title: '~45 seconds out',
      note: 'Watch it tick live into the expired state.',
      end: isoUtc(45 * 1000),
    },
    {
      title: 'Already expired',
      note: 'Renders the configured expired message — never negative numbers.',
      end: '2020-01-01T00:00:00Z',
    },
    {
      title: 'Creative wrap (goodgood theme)',
      note: 'Background PNG from the creative team with the timer rendered in a reserved zone — placeholder art, see creative/SPECS.md.',
      end: isoUtc(12 * 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000 + 30 * 60 * 1000),
      theme: 'goodgood',
    },
  ];
}

export default function PreviewPage() {
  const examples = buildExamples();

  return (
    <main style={{ maxWidth: 760, margin: '0 auto', padding: '40px 20px' }}>
      <h1 style={{ fontSize: 26, marginBottom: 4 }}>Email Countdown Timer</h1>
      <p style={{ color: '#6B7280', marginTop: 0, marginBottom: 32 }}>
        Each image below is a live 60-frame animated GIF generated by{' '}
        <code>/api/timer</code> at page load. Reload the page to regenerate.
      </p>

      <div style={{ display: 'grid', gap: 24, marginBottom: 32 }}>
        {examples.map((example) => {
          const url = `/api/timer?end=${encodeURIComponent(example.end)}${
            example.theme ? `&theme=${example.theme}` : ''
          }`;
          return (
            <section
              key={example.title}
              style={{
                background: '#FFFFFF',
                borderRadius: 8,
                padding: 24,
                boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
              }}
            >
              <h2 style={{ marginTop: 0, marginBottom: 4, fontSize: 18 }}>
                {example.title}
              </h2>
              <p style={{ color: '#6B7280', fontSize: 14, marginTop: 0 }}>{example.note}</p>
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={url}
                width={320}
                height={90}
                alt={`Countdown ending ${example.end}`}
                style={{ display: 'block', border: 0 }}
              />
              <code
                style={{
                  display: 'block',
                  marginTop: 10,
                  padding: '8px 12px',
                  background: '#F9FAFB',
                  border: '1px solid #E5E7EB',
                  borderRadius: 6,
                  fontSize: 13,
                  wordBreak: 'break-all',
                  userSelect: 'all',
                }}
              >
                {url}
              </code>
            </section>
          );
        })}
      </div>

      <PreviewControls />

      <p style={{ color: '#9CA3AF', fontSize: 13, marginTop: 32 }}>
        In production emails, append <code>&amp;uid=&lt;recipientId&gt;</code> for
        proxy-level uniqueness and optionally <code>&amp;theme=&lt;name&gt;</code>. See{' '}
        <code>adobe-embed/README.md</code> for ESP integration.
      </p>
    </main>
  );
}
